# Generated by Django 5.2.6 on 2025-11-06 00:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0002_alter_userprofile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recyclingbin',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='recyclingbin',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='recyclingbin',
            name='fullness',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recyclingbin',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='recyclingbin',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.CreateModel(
            name='BinVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recycling_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='recycling.recyclingbin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recycling_bin')},
            },
        ),
    ]
