# Generated by Django 5.2.7 on 2025-11-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0003_remove_recyclingbin_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
