# Generated by Django 5.2.7 on 2025-11-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0004_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
