# Generated by Django 5.2.7 on 2025-11-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0005_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
