# Generated by Django 5.2.7 on 2025-11-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0006_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sustainability_interests',
            field=models.TextField(blank=True, default=''),
        ),
    ]
