# Generated by Django 5.2.7 on 2025-12-08 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0007_userprofile_sustainability_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingbin',
            name='fullness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
